# docker-compose.yml
version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-order-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orderdb
    ports:
      - "3307:3306"
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql

  order-service:
    build: .
    container_name: order-service
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: orderdb
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      - db
